from tkinter import *
win=Tk()
win.title("TAB")
win.geometry('400x400')
l1=Label(win,text="LET THE JESUS DECIDE",fg="red",bg="black",font="Timess")
l1.grid(row=0,column=0)
l2=Label(win,text="ONE THOUSAND MILES",fg="blue",bg="pink",font="Helvetica 14 bold")
l2.grid(row=0,column=1)
l3=Label(win,text="LEAVE THE CROWD",fg="green",bg="grey",font="Algerian 18 bold")
l3.grid(row=1,column=0)
l4=Label(win,text="YOU ARE THE ONE",fg="yellow",bg="black",font="Algerian 18 bold")
l4.grid(row=1,column=1)
l5=PhotoImage(file="python-logo.png")
l5.grid(row=2,column=1)              
win.mainloop()
